import { Metadata } from "next";

import React, { ReactNode } from "react";

import { Header } from "@/layout";
import { ReduxProvider } from "@/layout/ReduxProvider";

import { ToastContainer } from "react-toastify";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Divar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ToastContainer position="top-center" style={{ zIndex: 9999 }} />

        <ReduxProvider>
          <Header />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
