import { Metadata } from "next";

import React, { ReactNode } from "react";

import { Header } from "@/layout/Header";
import { ReduxProvider } from "@/layout/ReduxProvider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Divar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ReduxProvider>
          <Header />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
