import "./globals.css";
import { Header } from "../../components/layout/Header";

export const metadata = {
  title: "Divar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
