import { Header } from "@/layout/Header";
import { ReduxProvider } from "@/layout/ReduxProvider";
import ModalProvider from "@/components/Ui/modal";
import "./globals.css";

export const metadata = {
  title: "Divar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ModalProvider>
          <ReduxProvider>
            <Header />

            {children}
          </ReduxProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
