import { Header } from "@/layout/Header";
import "./globals.css";
import { ReduxProvider } from "@/layout/ReduxProvider";

export const metadata = {
  title: "Divar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Header />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
